language: java

script: 
  - cd sdk ; mvn test
  - echo $test
  
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8


env:
  - Foo=bar
   
matrix:
  exclude:
    - jdk: openjdk7
      env: Foo=bar

#cache: true
